import { randomUUID } from 'node:crypto'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createServer } from 'node:http'
import type { Server } from 'node:http'
import type { AddressInfo } from 'node:net'
import { fileURLToPath } from 'node:url'
import { Client } from 'pg'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { ControlPostgresDatabase, PostgresComponentRegistryStore, runControlMigrations } from '@ontology/adapter-control-postgres'
import { FileSystemObjectStore, LocalImmutableBlobStore, PostgresArtifactRegistry } from '@ontology/adapter-blob-local'
import { LocalDocumentExtractionService, PostgresDocumentParseStore, publishGroundingDocumentSet } from '@ontology/adapter-extraction-document'
import { createCoreApi, createCoreLocalComposition, loadCoreExamples } from '@ontology/app-api'
import type { CoreLocalComposition } from '@ontology/app-api'
import type { ResourceRef, ScopeRef, VersionRef, AssetCandidateVersion, SemanticDefinitionRecord, ComponentVersionRecord } from '@ontology/contracts'
import { toolContext } from '../unit/component-registry-fixtures'
import { startPostgresContainer } from './postgres-container'
import type { PostgresContainer } from './postgres-container'

/**
 * W01 real-database acceptance for the default Core host composition.
 *
 * The whole v0.3 asset surface is exercised through the normal HTTP host over real PostgreSQL:
 * a definition candidate is generated by the model-backed generator, edited and reviewed, then a
 * rule candidate feeds an isolated synthetic validation, the published pack is committed and read
 * back from the dynamic catalogue. It also proves restart read-back (a second host over the same
 * database), tenant/space isolation and CAS conflict blocking. Nothing is mocked except the model
 * vendor, which answers one controlled definition-candidate response.
 */

const MIGRATIONS_DIR = fileURLToPath(new URL('../../migrations/control', import.meta.url))
const APP_PASSWORD = `chain_${randomUUID().replaceAll('-', '')}`
const MODEL_SECRET = 'test-only-controlled-definition-secret'
const DIGEST = `sha256:${'a'.repeat(64)}`
const POLICY_REF = { id: 'ontology.tbox.policy', version: '1.0.0', digest: DIGEST }

const generatedDefinition = {
  objects: [
    {
      logicalId: 'asset',
      displayName: 'Asset',
      businessMeaning: 'A maintained physical asset',
      suggestedReason: 'named in the source',
      sourceIndex: 0,
      identityAttributeIds: ['asset_code'],
    },
  ],
  attributes: [
    {
      logicalId: 'asset_code',
      displayName: 'Asset code',
      businessMeaning: 'The stable code that identifies an asset',
      suggestedReason: 'named in the source',
      sourceIndex: 0,
      objectLogicalId: 'asset',
      valueType: 'string',
      minCardinality: 1,
      maxCardinality: 1,
    },
    {
      logicalId: 'inspection_due',
      displayName: 'Inspection due',
      businessMeaning: 'Whether the next scheduled inspection is due',
      suggestedReason: 'named in the source',
      sourceIndex: 0,
      objectLogicalId: 'asset',
      valueType: 'boolean',
      minCardinality: 0,
      maxCardinality: 1,
    },
  ],
  relations: [],
}
let controlledDefinition: unknown = generatedDefinition

let container: PostgresContainer | undefined
let admin: Client | undefined
let appUrl = ''
let scope: ScopeRef
let otherScope: ScopeRef
let objectDirectory = ''
let composition: CoreLocalComposition | undefined
let api: ReturnType<typeof createCoreApi> | undefined
let baseUrl = ''
let otherComposition: CoreLocalComposition | undefined
let otherApi: ReturnType<typeof createCoreApi> | undefined
let otherBaseUrl = ''
let modelServer: Server | undefined
const modelRequests: string[] = []

async function startControlledModelServer(): Promise<string> {
  modelServer = createServer(async (request, response) => {
    const chunks: Buffer[] = []
    for await (const chunk of request) chunks.push(chunk as Buffer)
    modelRequests.push(Buffer.concat(chunks).toString('utf8'))
    response.writeHead(200, { 'content-type': 'text/event-stream', 'cache-control': 'no-cache' })
    const content = JSON.stringify(controlledDefinition)
    const frames = [
      { id: 'chatcmpl-chain', object: 'chat.completion.chunk', created: 1, model: 'synthetic-vendor-extractor', choices: [{ index: 0, delta: { content }, finish_reason: null }], usage: null },
      { id: 'chatcmpl-chain', object: 'chat.completion.chunk', created: 1, model: 'synthetic-vendor-extractor', choices: [{ index: 0, delta: {}, finish_reason: 'stop' }], usage: null },
      { id: 'chatcmpl-chain', object: 'chat.completion.chunk', created: 1, model: 'synthetic-vendor-extractor', choices: [], usage: { prompt_tokens: 10, completion_tokens: 12 } },
    ]
    for (const frame of frames) response.write(`data: ${JSON.stringify(frame)}\n\n`)
    response.write('data: [DONE]\n\n')
    response.end()
  })
  await new Promise<void>((resolve) => modelServer?.listen(0, '127.0.0.1', resolve))
  const address = modelServer.address() as AddressInfo
  return `http://127.0.0.1:${String(address.port)}`
}

async function seedScope(target: ScopeRef, slug: string): Promise<void> {
  if (admin === undefined) throw new Error('isolated PostgreSQL admin client is unavailable')
  await admin.query('INSERT INTO agent_platform.tenants (tenant_id, slug) VALUES ($1, $2)', [target.tenantId, slug])
  await admin.query('INSERT INTO agent_platform.spaces (tenant_id, space_id, name) VALUES ($1, $2, $3)', [target.tenantId, target.spaceId, slug])
}

async function startIsolatedDatabase(): Promise<void> {
  container = await startPostgresContainer()
  await runControlMigrations({ connectionString: container.adminUrl, migrationsDir: MIGRATIONS_DIR })
  admin = new Client({ connectionString: container.adminUrl })
  await admin.connect()
  scope = { tenantId: randomUUID(), spaceId: randomUUID() }
  otherScope = { tenantId: randomUUID(), spaceId: randomUUID() }
  await seedScope(scope, `chain-${scope.tenantId.slice(0, 8)}`)
  await seedScope(otherScope, `chain-other-${otherScope.tenantId.slice(0, 8)}`)
  const statement = await admin.query<{ statement: string }>(
    "SELECT format('ALTER ROLE ontology_app LOGIN PASSWORD %L', $1::text) AS statement",
    [APP_PASSWORD],
  )
  const alterStatement = statement.rows[0]?.statement
  if (alterStatement === undefined) throw new Error('could not prepare the non-owner application role')
  await admin.query(alterStatement)
  const appDatabase = new URL(container.adminUrl)
  appDatabase.username = 'ontology_app'
  appDatabase.password = APP_PASSWORD
  appUrl = appDatabase.toString()
}

function request(target: string, path: string, init?: RequestInit): Promise<Response> {
  return fetch(`${target}${path}`, { ...init, signal: AbortSignal.timeout(20_000) })
}

async function jsonBody(response: Response): Promise<Record<string, unknown>> {
  return await response.json() as Record<string, unknown>
}

async function failureDetail(response: Response): Promise<string> {
  return await response.text()
}

async function groundedSource(workspaceId: string): Promise<{ sourceRef: ResourceRef; documentSetRef: ResourceRef }> {
  const registry = new PostgresArtifactRegistry({ connectionString: appUrl, maxPoolSize: 2 })
  const documents = new PostgresDocumentParseStore({ connectionString: appUrl, maxPoolSize: 2 })
  try {
    const objectStore = new FileSystemObjectStore(objectDirectory)
    await objectStore.init()
    const blobs = new LocalImmutableBlobStore({ objectStore, registry })
    const ctx = toolContext(scope.tenantId, scope.spaceId, ['platform-admin', 'data-editor'], 'grounding-reviewer')
    const bytes = new TextEncoder().encode('An Asset is a maintained physical asset. Its stable asset_code identifies it. The boolean inspection_due records whether its next scheduled inspection is due.')
    const staged = await blobs.stage(bytes, { scopeRef: scope }, ctx)
    const sourceRef = (await blobs.publish({ scopeRef: scope, ...staged, mediaType: 'text/plain', purpose: 'document' }, ctx)).blobRef
    const parse = await new LocalDocumentExtractionService({ blobs, store: documents }).parse({ scopeRef: scope, originalRef: sourceRef }, ctx)
    const documentSetRef = await publishGroundingDocumentSet(blobs, { schemaVersion: '1.0.0', workspaceId, scopeRef: scope,
      sources: [{ sourceRef, state: 'approved', kind: 'document', parserVersion: parse.parserVersion, parseId: parse.parseId }] }, ctx)
    return { sourceRef, documentSetRef }
  } finally {
    await documents.close()
    await registry.close()
  }
}

async function startCompositionFor(scopeRef: ScopeRef): Promise<{ composition: CoreLocalComposition; api: ReturnType<typeof createCoreApi>; baseUrl: string }> {
  const built = await createCoreLocalComposition({
    databaseUrl: appUrl,
    objectDirectory,
    scopeRef,
    examples: loadCoreExamples({ targetScopeRef: scopeRef }),
    allowLocalOperator: true,
    modelsEnabled: true,
    jevEnabled: false,
    modelEnvironment: {
      CORE_ENABLE_MODELS: 'true',
      CORE_COMPANY_MODEL_BASE_URL: modelServerBaseUrl,
      CORE_COMPANY_MODEL_SECRET_REF: 'env:CORE_COMPANY_MODEL_API_KEY',
      CORE_COMPANY_MODEL_API_KEY: MODEL_SECRET,
      CORE_COMPANY_MODEL_PLATFORM_ID: 'core-company-extractor',
      CORE_COMPANY_MODEL_VENDOR_MODEL: 'synthetic-vendor-extractor',
      CORE_COMPANY_MODEL_PROTOCOL: 'openai-compatible',
    },
  })
  const app = createCoreApi(built.dependencies)
  const address = await app.listen({ host: '127.0.0.1', port: 0 })
  return { composition: built, api: app, baseUrl: address.replace(/\/$/u, '') }
}

let modelServerBaseUrl = ''
let publishedPackRef: { id: string; version: string; digest: string } | undefined
let workspaceId = ''
let chainExampleSetId = ''

async function mountedWorkspace(basePackRef: VersionRef, target = baseUrl, ground = true) {
  const create = await request(target, '/api/v1/industry-workspaces', {
    method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': randomUUID() },
    body: JSON.stringify({ namespace: `reuse-${randomUUID()}`, displayName: 'Incremental workspace B',
      boundary: { goals: ['extend assets'], included: ['registry'], excluded: ['pricing'], applicability: {} },
      documentSetRef: { id: randomUUID(), version: '1.0.0', digest: DIGEST, kind: 'artifact' } }),
  })
  if (create.status !== 201) throw new Error(`mounted workspace create failed: ${await failureDetail(create)}`)
  const workspaceId = (await jsonBody(create) as { data: { workspace: { workspaceId: string } } }).data.workspace.workspaceId
  const grounded = ground ? await groundedSource(workspaceId) : undefined
  const edit = await request(target, `/api/v1/industry-workspaces/${workspaceId}/draft-operations`, {
    method: 'POST', headers: { 'content-type': 'application/json', 'if-match': '1', 'idempotency-key': randomUUID() },
    body: JSON.stringify({ operation: 'edit', reason: 'mount the exact reusable package', basePackRef,
      ...(grounded === undefined ? {} : { documentSetRef: grounded.documentSetRef }) }),
  })
  if (edit.status !== 200) throw new Error(`mount base pin failed: ${await failureDetail(edit)}`)
  return { workspaceId, sourceRefs: grounded === undefined ? [] : [grounded.sourceRef] }
}

function generateMounted(workspace: { workspaceId: string; sourceRefs: ResourceRef[] }, target = baseUrl) {
  return request(target, `/api/v1/industry-workspaces/${workspace.workspaceId}/generations`, {
    method: 'POST', headers: { 'content-type': 'application/json', 'if-match': '2', 'idempotency-key': randomUUID() },
    body: JSON.stringify({ kinds: ['object', 'attribute', 'relation'], generationPolicyRef: POLICY_REF, sourceRefs: workspace.sourceRefs }),
  })
}

beforeAll(async () => {
  await startIsolatedDatabase()
  modelServerBaseUrl = await startControlledModelServer()
  objectDirectory = await mkdtemp(join(tmpdir(), 'ontology-core-composition-chain-'))
  const primary = await startCompositionFor(scope)
  composition = primary.composition
  api = primary.api
  baseUrl = primary.baseUrl
}, 240_000)

afterAll(async () => {
  await api?.close().catch(() => undefined)
  await composition?.close().catch(() => undefined)
  await otherApi?.close().catch(() => undefined)
  await otherComposition?.close().catch(() => undefined)
  await admin?.end().catch(() => undefined)
  await new Promise<void>((resolve) => modelServer?.close(() => resolve()))
  if (objectDirectory !== '') await rm(objectDirectory, { recursive: true, force: true }).catch(() => undefined)
  await container?.stop()
})

describe('the default Core host composition chain (real PostgreSQL)', () => {
  it('generates, edits, reviews, validates, publishes and reads back a pack, and blocks conflicts and cross-scope reads', async () => {
    const create = await request(baseUrl, '/api/v1/industry-workspaces', {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'idempotency-key': 'chain-workspace' },
      body: JSON.stringify({
        namespace: 'chain-acceptance',
        displayName: 'Chain acceptance workspace',
        boundary: { goals: ['model assets'], included: ['registry'], excluded: ['pricing'], applicability: {} },
        documentSetRef: { id: randomUUID(), version: '1.0.0', digest: DIGEST, kind: 'artifact' },
      }),
    })
    if (create.status !== 201) throw new Error(`workspace create failed: ${await failureDetail(create)}`)
    workspaceId = (await jsonBody(create) as { data: { workspace: { workspaceId: string } } }).data.workspace.workspaceId
    const { sourceRef, documentSetRef } = await groundedSource(workspaceId)
    const groundedDraft = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/draft-operations`, {
      method: 'POST', headers: { 'content-type': 'application/json', 'if-match': '1', 'idempotency-key': 'chain-approved-source' },
      body: JSON.stringify({ operation: 'edit', reason: 'attach the approved parsed source', documentSetRef }),
    })
    if (groundedDraft.status !== 200) throw new Error(`source attachment failed: ${await failureDetail(groundedDraft)}`)
    const workspaceRevision = (await jsonBody(groundedDraft) as { data: { workspace: { headRevision: string } } }).data.workspace.headRevision
    expect(workspaceRevision).toBe('2')

    const generation = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/generations`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': workspaceRevision, 'idempotency-key': 'chain-generation' },
      body: JSON.stringify({ kinds: ['object', 'attribute'], generationPolicyRef: POLICY_REF, sourceRefs: [sourceRef] }),
    })
    if (generation.status !== 201) throw new Error(`generation failed: ${await failureDetail(generation)}`)
    const generated = await jsonBody(generation) as { data: { candidates: { candidateId: string; kind: string; payload: Record<string, unknown> }[] } }
    if (generated.data.candidates.length < 3) throw new Error(`generation produced too few candidates: ${JSON.stringify(generated)}`)
    expect(generated.data.candidates.length).toBeGreaterThanOrEqual(3)
    expect(modelRequests.length).toBe(1)
    const attributeCandidate = generated.data.candidates.find(
      (candidate) => candidate.kind === 'attribute' && (candidate.payload as { logicalId?: string }).logicalId === 'inspection_due',
    )
    if (attributeCandidate === undefined) throw new Error('the generated attribute candidate is missing')

    const editedPayload = { ...attributeCandidate.payload, businessMeaning: 'Whether the next scheduled inspection is due' }
    const editBody = { payload: editedPayload, reason: 'clarify the business meaning' }
    const edit = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/candidates/${attributeCandidate.candidateId}/edits`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': workspaceRevision, 'idempotency-key': 'chain-edit' },
      body: JSON.stringify(editBody),
    })
    if (edit.status !== 200) throw new Error(`edit failed: ${await failureDetail(edit)}`)
    const editedRevision = (await jsonBody(edit) as { data: { created: boolean; candidates: { candidateId: string; replacesCandidateId?: string }[] } }).data.candidates[0]
    expect(editedRevision?.replacesCandidateId).toBe(attributeCandidate.candidateId)

    // Replaying the same Idempotency-Key never appends a second adjudication revision.
    const editReplay = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/candidates/${attributeCandidate.candidateId}/edits`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': workspaceRevision, 'idempotency-key': 'chain-edit' },
      body: JSON.stringify(editBody),
    })
    if (editReplay.status !== 200) throw new Error(`edit replay failed: ${await failureDetail(editReplay)}`)
    const replayBody = await jsonBody(editReplay) as { data: { created: boolean; adjudication: { adjudicationId: string } } }
    expect(replayBody.data.created).toBe(false)
    const adjudications = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/definition-adjudications`)
    expect((await jsonBody(adjudications) as { data: { adjudications: unknown[] } }).data.adjudications).toHaveLength(1)

    const review = await request(baseUrl, `/api/v1/candidates/${attributeCandidate.candidateId}/reviews`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': '0' },
      body: JSON.stringify({ decision: 'approve', reason: 'operator reviewed the generated attribute' }),
    })
    if (review.status !== 200) throw new Error(`review failed: ${await failureDetail(review)}`)
    const oldReview = await jsonBody(review) as { data: { contentDigest?: string; candidateId: string; decision: string } }
    expect(oldReview.data.candidateId).toBe(attributeCandidate.candidateId)
    expect(oldReview.data.contentDigest).toBeDefined()
    if (editedRevision === undefined) throw new Error('the edited current candidate revision is missing')
    const currentCandidateIds = [
      ...generated.data.candidates.filter((candidate) => candidate.candidateId !== attributeCandidate.candidateId).map((candidate) => candidate.candidateId),
      editedRevision.candidateId,
    ]
    for (const candidateId of currentCandidateIds) {
      const approval = await request(baseUrl, `/api/v1/candidates/${candidateId}/reviews`, {
        method: 'POST',
        headers: { 'content-type': 'application/json', 'if-match': '0' },
        body: JSON.stringify({ decision: 'approve', reason: 'operator reviewed this current declaration revision' }),
      })
      if (approval.status !== 200) throw new Error(`current revision approval failed: ${await failureDetail(approval)}`)
      expect((await jsonBody(approval) as { data: { contentDigest?: string } }).data.contentDigest).toBeDefined()
    }
    const reviewHistory = await request(baseUrl, `/api/v1/candidates/${attributeCandidate.candidateId}/reviews`)
    expect((await jsonBody(reviewHistory) as { data: { reviews: { candidateId: string; decision: string }[] } }).data.reviews)
      .toEqual(expect.arrayContaining([expect.objectContaining({ candidateId: attributeCandidate.candidateId, decision: 'approve' })]))

    const rule = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/rule-action-candidates/ingest`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': workspaceRevision, 'idempotency-key': 'chain-rule' },
      body: JSON.stringify({
        rules: [{
          kind: 'rule',
          ruleId: 'inspection_due_rule',
          displayName: 'Inspection due rule',
          businessMeaning: 'The next inspection is due',
          suggestedReason: 'derived from the registry',
          objectId: 'asset',
          condition: { op: 'compare', attributeId: 'inspection_due', operator: 'eq', value: true },
          exceptions: [],
          ruleDependencies: [],
        }],
      }),
    })
    if (rule.status !== 201) throw new Error(`rule ingest failed: ${await failureDetail(rule)}`)
    const ruleCandidateId = (await jsonBody(rule) as { data: { rules: { candidateId: string }[] } }).data.rules[0]?.candidateId
    if (ruleCandidateId === undefined) throw new Error('the ingested rule candidate id is missing')
    const enableRule = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/rule-action-candidates/${ruleCandidateId}/enable`, {
      method: 'POST',
      headers: { 'if-match': workspaceRevision },
    })
    if (enableRule.status !== 200) throw new Error(`rule enable failed: ${await failureDetail(enableRule)}`)
    expect((await jsonBody(enableRule) as { data: { created: boolean; candidate: { lifecycle: string } } }).data.candidate.lifecycle).toBe('enabled')
    const ruleReview = await request(baseUrl, `/api/v1/candidates/${ruleCandidateId}/reviews`, {
      method: 'POST', headers: { 'content-type': 'application/json', 'if-match': '0' },
      body: JSON.stringify({ decision: 'approve', reason: 'approve the enabled rule and its exact content' }),
    })
    expect(ruleReview.status).toBe(200)

    const exampleSet = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/synthetic-example-sets`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': workspaceRevision, 'idempotency-key': 'chain-example-set' },
      body: JSON.stringify({
        caseKinds: ['contradiction'],
        cases: [{
          caseId: 'case-due',
          caseKind: 'contradiction',
          objectTypeRef: 'asset',
          fields: [{ fieldId: 'inspection_due', value: true }],
        }],
        expectations: [{
          expectationId: 'exp-due',
          caseId: 'case-due',
          kind: 'rule',
          ruleId: 'inspection_due_rule',
          expected: 'true',
          origin: 'authored_oracle',
          reason: 'the oracle asserts the rule fires',
          confirmedBy: 'reviewer-1',
          confirmedAt: '2026-09-30T00:00:00Z',
        }],
      }),
    })
    if (exampleSet.status !== 201) throw new Error(`synthetic example set failed: ${await failureDetail(exampleSet)}`)
    const exampleSetId = (await jsonBody(exampleSet) as { data: { exampleSet: { exampleSetId: string } } }).data.exampleSet.exampleSetId
    chainExampleSetId = exampleSetId

    const validation = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/validations`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': workspaceRevision, 'idempotency-key': 'chain-validation' },
      body: JSON.stringify({ exampleSetId }),
    })
    if (validation.status !== 201) throw new Error(`validation failed: ${await failureDetail(validation)}`)
    const report = (await jsonBody(validation) as { data: { validation: { validationId: string; publishable: boolean; semanticPublished: { passed: boolean }; deploymentExecutable: { passed: boolean } } } }).data.validation
    expect(report.semanticPublished.passed, JSON.stringify(report)).toBe(true)
    expect(report.deploymentExecutable.passed).toBe(true)
    expect(report.publishable).toBe(true)

    // CAS conflict blocking: a stale revision may not publish the pack.
    const stalePublish = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/publications`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': '999', 'idempotency-key': 'chain-publish-stale' },
      body: JSON.stringify({ packId: 'chain-pack', version: '1.0.0', validationId: report.validationId }),
    })
    expect(stalePublish.status).toBe(409)

    const publish = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/publications`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': workspaceRevision, 'idempotency-key': 'chain-publish' },
      body: JSON.stringify({ packId: 'chain-pack', version: '1.0.0', validationId: report.validationId }),
    })
    if (publish.status !== 201) throw new Error(`publish failed: ${await failureDetail(publish)}`)
    const published = await jsonBody(publish) as { data: { packRef: { id: string; version: string; digest: string } } }
    publishedPackRef = published.data.packRef
    expect(publishedPackRef.id).toBe('chain-acceptance.chain-pack')
    expect(publishedPackRef.version).toBe('1.0.0')

    const catalogue = await request(baseUrl, '/api/v1/industry-packs')
    if (catalogue.status !== 200) throw new Error(`catalogue read failed: ${await failureDetail(catalogue)}`)
    const packs = (await jsonBody(catalogue) as { data: { packs: { packRef: { id: string; version: string } }[] } }).data.packs
    expect(packs.some((entry) => entry.packRef.id === publishedPackRef?.id && entry.packRef.version === '1.0.0')).toBe(true)

    // Tenant/space isolation: another scope sees neither the workspace nor the published pack.
    const other = await startCompositionFor(otherScope)
    otherComposition = other.composition
    otherApi = other.api
    otherBaseUrl = other.baseUrl
    const foreignAdjudications = await request(otherBaseUrl, `/api/v1/industry-workspaces/${workspaceId}/definition-adjudications`)
    expect(foreignAdjudications.status).toBe(200)
    const foreignAdjudicationRows = (await jsonBody(foreignAdjudications) as { data: { adjudications: unknown[] } }).data.adjudications
    expect(foreignAdjudicationRows).toHaveLength(0)
    const foreignCatalogue = await request(otherBaseUrl, '/api/v1/industry-packs')
    expect(foreignCatalogue.status).toBe(200)
    const foreignPacks = (await jsonBody(foreignCatalogue) as { data: { packs: unknown[] } }).data.packs
    expect(foreignPacks).toHaveLength(0)
  }, 240_000)

  it('loads newly published package A in workspace B, persists incremental references and explains conflicts', async () => {
    const pin = publishedPackRef
    if (pin === undefined || admin === undefined) throw new Error('the initial publication is missing')
    const workspaceB = await mountedWorkspace(pin)
    const object = { displayName: 'Asset', businessMeaning: 'a product in a financial catalogue', suggestedReason: 'source', sourceIndex: 0, identityAttributeIds: [] }
    controlledDefinition = {
      objects: [{ ...object, logicalId: 'asset', displayName: 'Renamed Asset', businessMeaning: 'a maintained physical asset', identityAttributeIds: ['asset_code'] },
        { ...object, logicalId: 'catalog_product' }],
      attributes: [
        { logicalId: 'condition', displayName: 'Condition', businessMeaning: 'condition of the maintained asset', suggestedReason: 'source', sourceIndex: 0, objectLogicalId: 'asset', valueType: 'boolean' },
        { logicalId: 'inspection_due', displayName: 'Inspection due', businessMeaning: 'a model type conflict', suggestedReason: 'source', sourceIndex: 0, objectLogicalId: 'asset', valueType: 'string' },
      ],
      relations: [{ logicalId: 'product_requires_asset', displayName: 'Requires asset', businessMeaning: 'product requires maintained asset', suggestedReason: 'source', sourceIndex: 0,
        fromObjectLogicalId: 'catalog_product', toObjectLogicalId: 'asset' }],
    }
    try {
      const before = modelRequests.length
      const response = await generateMounted(workspaceB)
      if (response.status !== 201) throw new Error(`incremental generation failed: ${await failureDetail(response)}`)
      const view = (await jsonBody(response) as { data: { candidates: AssetCandidateVersion[] } }).data
      expect(view.candidates).toHaveLength(5)
      const canonical = view.candidates.find((candidate) => candidate.logicalId === 'asset')
      expect(canonical?.payload.displayName).toBe('Asset')
      expect(canonical?.payload.conflicts).toContainEqual({ kind: 'terminology_mismatch',
        message: 'the mounted asset names "asset" as "Asset", not "Renamed Asset"', relatedLogicalIds: ['asset'] })
      expect(view.candidates.find((candidate) => candidate.logicalId === 'catalog_product')?.payload.displayName).toBe('Asset')
      const condition = view.candidates.find((candidate) => candidate.logicalId === 'condition')
      expect(condition?.payload).toMatchObject({ objectLogicalId: 'asset' })
      expect(condition?.issues.some((issue) => issue.code === 'ENDPOINT_UNRESOLVED')).toBe(false)
      expect(view.candidates.find((candidate) => candidate.logicalId === 'inspection_due')?.payload.conflicts).toContainEqual({
        kind: 'terminology_mismatch', message: 'mounted attribute type is boolean', relatedLogicalIds: ['inspection_due'] })
      expect(view.candidates.find((candidate) => candidate.kind === 'relation')?.issues.some((issue) => issue.code === 'ENDPOINT_UNRESOLVED')).toBe(false)
      expect(modelRequests.length).toBe(before + 1)
      const definition = await admin.query<{ definition: SemanticDefinitionRecord }>(
        'SELECT definition FROM agent_platform.semantic_definition_versions WHERE tenant_id=$1 AND space_id=$2 AND namespace=$3 AND version=$4',
        [scope.tenantId, scope.spaceId, 'chain-acceptance', pin.version])
      const requestText = modelRequests.at(-1) ?? ''
      const record = definition.rows[0]?.definition
      if (record === undefined) throw new Error('the persisted definition is missing')
      expect(requestText).toContain(pin.digest)
      expect(requestText).toContain(record.ref.digest)
      expect(requestText).toContain('identityScopes')
      expect(requestText).toContain('standardProvenance')
      const persisted = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceB.workspaceId}/candidates`)
      expect((await jsonBody(persisted) as { data: { candidates: AssetCandidateVersion[] } }).data.candidates).toEqual(view.candidates)
      const draft = await admin.query<{ base_pack_ref: VersionRef }>(
        "SELECT body->'basePackRef' AS base_pack_ref FROM agent_platform.asset_draft_versions WHERE tenant_id=$1 AND space_id=$2 AND workspace_id=$3 AND revision=2",
        [scope.tenantId, scope.spaceId, workspaceB.workspaceId])
      expect(draft.rows[0]?.base_pack_ref).toEqual(pin)
    } finally {
      controlledDefinition = generatedDefinition
    }
  })

  it('preserves the persisted static profile pin and its identity/unit declarations through the default host', async () => {
    const spec = Object.values(composition?.dependencies.profileSpecsByScenario ?? {})[0]
    if (spec === undefined) throw new Error('the mounted static profile is missing')
    const workspace = await mountedWorkspace(spec.industryRef)
    const response = await generateMounted(workspace)
    if (response.status !== 201) throw new Error(`static mounted generation failed: ${await failureDetail(response)}`)
    expect(modelRequests.at(-1)).toContain(spec.industryRef.digest)
    expect(modelRequests.at(-1)).toContain('identityScopes')
    expect(modelRequests.at(-1)).toContain('unitCode')
    expect(modelRequests.at(-1)).toContain('standardProvenance')
  })

  it('rejects a wrong digest or another tenant’s private base before calling the model', async () => {
    const pin = publishedPackRef
    if (pin === undefined) throw new Error('the initial publication is missing')
    for (const attempt of [
      { ref: { ...pin, digest: DIGEST }, target: baseUrl, status: 409 },
      { ref: pin, target: otherBaseUrl, status: 409 },
    ]) {
      const workspace = await mountedWorkspace(attempt.ref, attempt.target, false)
      const before = modelRequests.length
      const response = await generateMounted(workspace, attempt.target)
      expect(response.status).toBe(attempt.status)
      expect(modelRequests.length).toBe(before)
      const batches = await request(attempt.target, `/api/v1/industry-workspaces/${workspace.workspaceId}/generations`)
      expect((await jsonBody(batches) as { data: { batches: unknown[] } }).data.batches).toHaveLength(0)
    }
  })

  it('carries a breaking-change strategy through the ordinary validation/publication HTTP routes and preserves v1', async () => {
    const firstRef = publishedPackRef
    if (firstRef === undefined) throw new Error('the initial publication is missing')
    const workspace = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}`)
    const revision = (await jsonBody(workspace) as { data: { workspace: { headRevision: string } } }).data.workspace.headRevision
    const candidates = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/candidates`)
    const code = (await jsonBody(candidates) as { data: { candidates: { candidateId: string; payload: Record<string, unknown> }[] } }).data.candidates.find((candidate) => candidate.payload['logicalId'] === 'asset_code')
    if (code === undefined) throw new Error('the current code declaration is missing')
    const edit = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/candidates/${code.candidateId}/edits`, {
      method: 'POST', headers: { 'content-type': 'application/json', 'if-match': revision, 'idempotency-key': 'chain-breaking-edit' },
      body: JSON.stringify({ payload: { ...code.payload, valueType: 'number' }, reason: 'code semantics are now numeric' }),
    })
    if (edit.status !== 200) throw new Error(`breaking edit failed: ${await failureDetail(edit)}`)
    const replacement = (await jsonBody(edit) as { data: { candidates: { candidateId: string }[] } }).data.candidates[0]
    if (replacement === undefined) throw new Error('the replacement is missing')
    const approval = await request(baseUrl, `/api/v1/candidates/${replacement.candidateId}/reviews`, {
      method: 'POST', headers: { 'content-type': 'application/json', 'if-match': '0' },
      body: JSON.stringify({ decision: 'approve', reason: 'reviewed numeric code definition' }),
    })
    expect(approval.status).toBe(200)
    const blocked = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/validations`, {
      method: 'POST', headers: { 'content-type': 'application/json', 'if-match': revision, 'idempotency-key': 'chain-breaking-no-strategy' },
      body: JSON.stringify({ exampleSetId: chainExampleSetId }),
    })
    expect(blocked.status).toBe(201)
    const blockedReport = (await jsonBody(blocked) as { data: { validation: { semanticPublished: { passed: boolean }; definition: { blockers: { code: string }[] } } } }).data.validation
    expect(blockedReport.semanticPublished.passed).toBe(false)
    expect(blockedReport.definition.blockers.map((finding) => finding.code)).toContain('REVISION_STRATEGY_REQUIRED')
    const invalid = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/publications`, {
      method: 'POST', headers: { 'content-type': 'application/json', 'if-match': revision, 'idempotency-key': 'chain-invalid-strategy' },
      body: JSON.stringify({ packId: 'chain-pack', version: '2.0.0', validationId: randomUUID(), strategy: { kind: 'invented', reason: 'bad' } }),
    })
    expect(invalid.status).toBe(400)
    const strategy = { kind: 'new_version', reason: 'explicitly publish numeric code semantics as v2' }
    const validated = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/validations`, {
      method: 'POST', headers: { 'content-type': 'application/json', 'if-match': revision, 'idempotency-key': 'chain-breaking-with-strategy' },
      body: JSON.stringify({ exampleSetId: chainExampleSetId, strategy }),
    })
    expect(validated.status).toBe(201)
    const report = (await jsonBody(validated) as { data: { validation: { validationId: string; strategy: unknown; semanticPublished: { passed: boolean } } } }).data.validation
    expect(report.semanticPublished.passed).toBe(true)
    expect(report.strategy).toEqual(strategy)
    const publication = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/publications`, {
      method: 'POST', headers: { 'content-type': 'application/json', 'if-match': revision, 'idempotency-key': 'chain-breaking-publish' },
      body: JSON.stringify({ packId: 'chain-pack', version: '2.0.0', validationId: report.validationId, strategy }),
    })
    if (publication.status !== 201) throw new Error(`breaking publication failed: ${await failureDetail(publication)}`)
    const asset = (await jsonBody(publication) as { data: { packRef: { id: string; version: string; digest: string }; pack: { strategy: unknown; diff: { breakingChanges: { change: string }[] } } } }).data
    expect(asset.pack.strategy).toEqual(strategy)
    expect(asset.pack.diff.breakingChanges.map((change) => change.change)).toContain('VALUE_TYPE_CHANGED')
    publishedPackRef = asset.packRef
    const catalogue = await request(baseUrl, '/api/v1/industry-packs')
    expect((await jsonBody(catalogue) as { data: { packs: { packRef: unknown }[] } }).data.packs.map((pack) => pack.packRef)).toContainEqual(firstRef)
  }, 240_000)

  it('reads the published pack back through a fresh host over the same database after a restart', async () => {
    await api?.close()
    api = undefined
    await composition?.close()
    composition = undefined

    const restarted = await startCompositionFor(scope)
    composition = restarted.composition
    api = restarted.api
    baseUrl = restarted.baseUrl

    expect(publishedPackRef).toBeDefined()
    const catalogue = await request(baseUrl, '/api/v1/industry-packs')
    if (catalogue.status !== 200) throw new Error(`restart catalogue read failed: ${await failureDetail(catalogue)}`)
    const packs = (await jsonBody(catalogue) as { data: { packs: { packRef: { id: string; version: string; digest: string } }[] } }).data.packs
    const restored = packs.find((entry) => entry.packRef.id === publishedPackRef?.id && entry.packRef.version === publishedPackRef?.version)
    expect(restored?.packRef.digest).toBe(publishedPackRef?.digest)

    const exportResponse = await request(baseUrl, `/api/v1/industry-packs/${encodeURIComponent(publishedPackRef?.id ?? '')}/export?version=${encodeURIComponent(publishedPackRef?.version ?? '')}`)
    if (exportResponse.status !== 200) throw new Error(`pack export failed: ${await failureDetail(exportResponse)}`)
    const bundle = await jsonBody(exportResponse) as { data: { packRef: { id: string; version: string } } }
    expect(bundle.data.packRef.id).toBe(publishedPackRef?.id)
    expect(bundle.data.packRef.version).toBe(publishedPackRef?.version)
  }, 240_000)

  it('rechecks actual scoped registry deprecation and retirement before fresh generation through the current host', async () => {
    const spec = Object.values(composition?.dependencies.profileSpecsByScenario ?? {})[0]
    if (spec === undefined) throw new Error('the mounted static profile is missing')
    const workspace = await mountedWorkspace(spec.industryRef)
    const initial = await generateMounted(workspace)
    expect(initial.status).toBe(201)
    const database = new ControlPostgresDatabase({ connectionString: appUrl, maxPoolSize: 2 })
    try {
      const registry = new PostgresComponentRegistryStore(database)
      const ctx = toolContext(scope.tenantId, scope.spaceId, ['platform-admin'], 'retirement-reviewer')
      const key = { kind: 'industry_pack' as const, id: spec.industryRef.id, version: spec.industryRef.version }
      const found = await registry.findVersion(key, scope, ctx)
      if (found === undefined) throw new Error('the exact static registered component is missing')
      let record: ComponentVersionRecord = found
      const manifest = record.manifest
      for (const to of ['deprecated', 'retired'] as const) {
        const at = new Date().toISOString()
        const next: ComponentVersionRecord = { ...record, lifecycleState: to, ...(to === 'deprecated' ? { deprecatedAt: at } : { retiredAt: at }) }
        await registry.applyTransition(scope, key, record.lifecycleState, next, {
          fromState: record.lifecycleState, toState: to, digest: record.manifestRef.digest,
          payloadDigest: DIGEST, idempotencyKey: `retire-${randomUUID()}`, occurredAt: at, actor: 'retirement-reviewer',
        }, ctx)
        record = next
        expect((await registry.findVersion(key, scope, ctx))?.lifecycleState).toBe(to)
        expect(record.manifest).toEqual(manifest)
        const before = modelRequests.length
        const blocked = await generateMounted(workspace)
        expect(blocked.status).toBe(422)
        const failure = await jsonBody(blocked) as { error: { reasons?: string[]; message: string } }
        expect(failure.error.message).toContain(to)
        expect(modelRequests.length).toBe(before)
      }
      const otherCtx = toolContext(otherScope.tenantId, otherScope.spaceId, ['platform-admin'], 'other-retirement-reviewer')
      expect((await registry.findVersion(key, otherScope, otherCtx))?.lifecycleState).toBe('active')
      await expect(registry.findVersion(key, otherScope, ctx)).rejects.toMatchObject({ code: 'SCOPE_MISMATCH' })
    } finally {
      await database.close()
    }
  })
})
