import { randomUUID } from 'node:crypto'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createServer } from 'node:http'
import type { Server } from 'node:http'
import type { AddressInfo } from 'node:net'
import { fileURLToPath } from 'node:url'
import { Client } from 'pg'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { runControlMigrations } from '@ontology/adapter-control-postgres'
import { createCoreApi, createCoreLocalComposition, loadCoreExamples } from '@ontology/app-api'
import type { CoreLocalComposition } from '@ontology/app-api'
import type { ScopeRef } from '@ontology/contracts'
import { startPostgresContainer } from './postgres-container'
import type { PostgresContainer } from './postgres-container'

/**
 * W01 real-database acceptance for the default Core host composition.
 *
 * The whole v0.3 asset surface is exercised through the normal HTTP host over real PostgreSQL:
 * a definition candidate is generated by the model-backed generator, edited and reviewed, then a
 * rule candidate feeds an isolated synthetic validation, the published pack is committed and read
 * back from the dynamic catalogue. It also proves restart read-back (a second host over the same
 * database), tenant/space isolation and CAS conflict blocking. Nothing is mocked except the model
 * vendor, which answers one controlled definition-candidate response.
 */

const MIGRATIONS_DIR = fileURLToPath(new URL('../../migrations/control', import.meta.url))
const APP_PASSWORD = `chain_${randomUUID().replaceAll('-', '')}`
const MODEL_SECRET = 'test-only-controlled-definition-secret'
const DIGEST = `sha256:${'a'.repeat(64)}`
const POLICY_REF = { id: 'ontology.tbox.policy', version: '1.0.0', digest: DIGEST }

const generatedDefinition = {
  objects: [
    {
      logicalId: 'asset',
      displayName: 'Asset',
      businessMeaning: 'A maintained physical asset',
      suggestedReason: 'named in the source',
      identityAttributeIds: ['asset_code'],
    },
  ],
  attributes: [
    {
      logicalId: 'asset_code',
      displayName: 'Asset code',
      businessMeaning: 'The stable code that identifies an asset',
      suggestedReason: 'named in the source',
      objectLogicalId: 'asset',
      valueType: 'string',
      minCardinality: 1,
      maxCardinality: 1,
    },
    {
      logicalId: 'inspection_due',
      displayName: 'Inspection due',
      businessMeaning: 'Whether the next scheduled inspection is due',
      suggestedReason: 'named in the source',
      objectLogicalId: 'asset',
      valueType: 'boolean',
      minCardinality: 0,
      maxCardinality: 1,
    },
  ],
  relations: [],
}

let container: PostgresContainer | undefined
let admin: Client | undefined
let appUrl = ''
let scope: ScopeRef
let otherScope: ScopeRef
let objectDirectory = ''
let composition: CoreLocalComposition | undefined
let api: ReturnType<typeof createCoreApi> | undefined
let baseUrl = ''
let otherComposition: CoreLocalComposition | undefined
let otherApi: ReturnType<typeof createCoreApi> | undefined
let otherBaseUrl = ''
let modelServer: Server | undefined
const modelRequests: string[] = []

async function startControlledModelServer(): Promise<string> {
  modelServer = createServer(async (request, response) => {
    const chunks: Buffer[] = []
    for await (const chunk of request) chunks.push(chunk as Buffer)
    modelRequests.push(Buffer.concat(chunks).toString('utf8'))
    response.writeHead(200, { 'content-type': 'text/event-stream', 'cache-control': 'no-cache' })
    const content = JSON.stringify(generatedDefinition)
    const frames = [
      { id: 'chatcmpl-chain', object: 'chat.completion.chunk', created: 1, model: 'synthetic-vendor-extractor', choices: [{ index: 0, delta: { content }, finish_reason: null }], usage: null },
      { id: 'chatcmpl-chain', object: 'chat.completion.chunk', created: 1, model: 'synthetic-vendor-extractor', choices: [{ index: 0, delta: {}, finish_reason: 'stop' }], usage: null },
      { id: 'chatcmpl-chain', object: 'chat.completion.chunk', created: 1, model: 'synthetic-vendor-extractor', choices: [], usage: { prompt_tokens: 10, completion_tokens: 12 } },
    ]
    for (const frame of frames) response.write(`data: ${JSON.stringify(frame)}\n\n`)
    response.write('data: [DONE]\n\n')
    response.end()
  })
  await new Promise<void>((resolve) => modelServer?.listen(0, '127.0.0.1', resolve))
  const address = modelServer.address() as AddressInfo
  return `http://127.0.0.1:${String(address.port)}`
}

async function seedScope(target: ScopeRef, slug: string): Promise<void> {
  if (admin === undefined) throw new Error('isolated PostgreSQL admin client is unavailable')
  await admin.query('INSERT INTO agent_platform.tenants (tenant_id, slug) VALUES ($1, $2)', [target.tenantId, slug])
  await admin.query('INSERT INTO agent_platform.spaces (tenant_id, space_id, name) VALUES ($1, $2, $3)', [target.tenantId, target.spaceId, slug])
}

async function startIsolatedDatabase(): Promise<void> {
  container = await startPostgresContainer()
  await runControlMigrations({ connectionString: container.adminUrl, migrationsDir: MIGRATIONS_DIR })
  admin = new Client({ connectionString: container.adminUrl })
  await admin.connect()
  scope = { tenantId: randomUUID(), spaceId: randomUUID() }
  otherScope = { tenantId: randomUUID(), spaceId: randomUUID() }
  await seedScope(scope, `chain-${scope.tenantId.slice(0, 8)}`)
  await seedScope(otherScope, `chain-other-${otherScope.tenantId.slice(0, 8)}`)
  const statement = await admin.query<{ statement: string }>(
    "SELECT format('ALTER ROLE ontology_app LOGIN PASSWORD %L', $1::text) AS statement",
    [APP_PASSWORD],
  )
  const alterStatement = statement.rows[0]?.statement
  if (alterStatement === undefined) throw new Error('could not prepare the non-owner application role')
  await admin.query(alterStatement)
  const appDatabase = new URL(container.adminUrl)
  appDatabase.username = 'ontology_app'
  appDatabase.password = APP_PASSWORD
  appUrl = appDatabase.toString()
}

function request(target: string, path: string, init?: RequestInit): Promise<Response> {
  return fetch(`${target}${path}`, { ...init, signal: AbortSignal.timeout(20_000) })
}

async function jsonBody(response: Response): Promise<Record<string, unknown>> {
  return await response.json() as Record<string, unknown>
}

async function failureDetail(response: Response): Promise<string> {
  return await response.text()
}

async function startCompositionFor(scopeRef: ScopeRef): Promise<{ composition: CoreLocalComposition; api: ReturnType<typeof createCoreApi>; baseUrl: string }> {
  const built = await createCoreLocalComposition({
    databaseUrl: appUrl,
    objectDirectory,
    scopeRef,
    examples: loadCoreExamples({ targetScopeRef: scopeRef }),
    allowLocalOperator: true,
    modelsEnabled: true,
    jevEnabled: false,
    modelEnvironment: {
      CORE_ENABLE_MODELS: 'true',
      CORE_COMPANY_MODEL_BASE_URL: modelServerBaseUrl,
      CORE_COMPANY_MODEL_SECRET_REF: 'env:CORE_COMPANY_MODEL_API_KEY',
      CORE_COMPANY_MODEL_API_KEY: MODEL_SECRET,
      CORE_COMPANY_MODEL_PLATFORM_ID: 'core-company-extractor',
      CORE_COMPANY_MODEL_VENDOR_MODEL: 'synthetic-vendor-extractor',
      CORE_COMPANY_MODEL_PROTOCOL: 'openai-compatible',
    },
  })
  const app = createCoreApi(built.dependencies)
  const address = await app.listen({ host: '127.0.0.1', port: 0 })
  return { composition: built, api: app, baseUrl: address.replace(/\/$/u, '') }
}

let modelServerBaseUrl = ''
let publishedPackRef: { id: string; version: string; digest: string } | undefined
let workspaceId = ''

beforeAll(async () => {
  await startIsolatedDatabase()
  modelServerBaseUrl = await startControlledModelServer()
  objectDirectory = await mkdtemp(join(tmpdir(), 'ontology-core-composition-chain-'))
  const primary = await startCompositionFor(scope)
  composition = primary.composition
  api = primary.api
  baseUrl = primary.baseUrl
}, 240_000)

afterAll(async () => {
  await api?.close().catch(() => undefined)
  await composition?.close().catch(() => undefined)
  await otherApi?.close().catch(() => undefined)
  await otherComposition?.close().catch(() => undefined)
  await admin?.end().catch(() => undefined)
  await new Promise<void>((resolve) => modelServer?.close(() => resolve()))
  if (objectDirectory !== '') await rm(objectDirectory, { recursive: true, force: true }).catch(() => undefined)
  await container?.stop()
})

describe('the default Core host composition chain (real PostgreSQL)', () => {
  it('generates, edits, reviews, validates, publishes and reads back a pack, and blocks conflicts and cross-scope reads', async () => {
    const create = await request(baseUrl, '/api/v1/industry-workspaces', {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'idempotency-key': 'chain-workspace' },
      body: JSON.stringify({
        namespace: 'chain-acceptance',
        displayName: 'Chain acceptance workspace',
        boundary: { goals: ['model assets'], included: ['registry'], excluded: ['pricing'], applicability: {} },
        documentSetRef: { id: randomUUID(), version: '1.0.0', digest: DIGEST, kind: 'artifact' },
      }),
    })
    if (create.status !== 201) throw new Error(`workspace create failed: ${await failureDetail(create)}`)
    workspaceId = (await jsonBody(create) as { data: { workspace: { workspaceId: string } } }).data.workspace.workspaceId

    const generation = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/generations`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': '1', 'idempotency-key': 'chain-generation' },
      body: JSON.stringify({ kinds: ['object', 'attribute'], generationPolicyRef: POLICY_REF }),
    })
    if (generation.status !== 201) throw new Error(`generation failed: ${await failureDetail(generation)}`)
    const generated = await jsonBody(generation) as { data: { candidates: { candidateId: string; kind: string; payload: Record<string, unknown> }[] } }
    if (generated.data.candidates.length < 3) throw new Error(`generation produced too few candidates: ${JSON.stringify(generated)}`)
    expect(generated.data.candidates.length).toBeGreaterThanOrEqual(3)
    expect(modelRequests.length).toBe(1)
    const attributeCandidate = generated.data.candidates.find(
      (candidate) => candidate.kind === 'attribute' && (candidate.payload as { logicalId?: string }).logicalId === 'inspection_due',
    )
    if (attributeCandidate === undefined) throw new Error('the generated attribute candidate is missing')

    const editedPayload = { ...attributeCandidate.payload, businessMeaning: 'Whether the next scheduled inspection is due' }
    const editBody = { payload: editedPayload, reason: 'clarify the business meaning' }
    const edit = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/candidates/${attributeCandidate.candidateId}/edits`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': '1', 'idempotency-key': 'chain-edit' },
      body: JSON.stringify(editBody),
    })
    if (edit.status !== 200) throw new Error(`edit failed: ${await failureDetail(edit)}`)
    const editedRevision = (await jsonBody(edit) as { data: { created: boolean; candidates: { candidateId: string; replacesCandidateId?: string }[] } }).data.candidates[0]
    expect(editedRevision?.replacesCandidateId).toBe(attributeCandidate.candidateId)

    // Replaying the same Idempotency-Key never appends a second adjudication revision.
    const editReplay = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/candidates/${attributeCandidate.candidateId}/edits`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': '1', 'idempotency-key': 'chain-edit' },
      body: JSON.stringify(editBody),
    })
    if (editReplay.status !== 200) throw new Error(`edit replay failed: ${await failureDetail(editReplay)}`)
    const replayBody = await jsonBody(editReplay) as { data: { created: boolean; adjudication: { adjudicationId: string } } }
    expect(replayBody.data.created).toBe(false)
    const adjudications = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/definition-adjudications`)
    expect((await jsonBody(adjudications) as { data: { adjudications: unknown[] } }).data.adjudications).toHaveLength(1)

    const review = await request(baseUrl, `/api/v1/candidates/${attributeCandidate.candidateId}/reviews`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': '0' },
      body: JSON.stringify({ decision: 'approve', reason: 'operator reviewed the generated attribute' }),
    })
    if (review.status !== 200) throw new Error(`review failed: ${await failureDetail(review)}`)

    const rule = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/rule-action-candidates/ingest`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': '1', 'idempotency-key': 'chain-rule' },
      body: JSON.stringify({
        rules: [{
          kind: 'rule',
          ruleId: 'inspection_due_rule',
          displayName: 'Inspection due rule',
          businessMeaning: 'The next inspection is due',
          suggestedReason: 'derived from the registry',
          objectId: 'asset',
          condition: { op: 'compare', attributeId: 'inspection_due', operator: 'eq', value: true },
          exceptions: [],
          ruleDependencies: [],
        }],
      }),
    })
    if (rule.status !== 201) throw new Error(`rule ingest failed: ${await failureDetail(rule)}`)
    const ruleCandidateId = (await jsonBody(rule) as { data: { rules: { candidateId: string }[] } }).data.rules[0]?.candidateId
    if (ruleCandidateId === undefined) throw new Error('the ingested rule candidate id is missing')
    const enableRule = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/rule-action-candidates/${ruleCandidateId}/enable`, {
      method: 'POST',
      headers: { 'if-match': '1' },
    })
    if (enableRule.status !== 200) throw new Error(`rule enable failed: ${await failureDetail(enableRule)}`)
    expect((await jsonBody(enableRule) as { data: { created: boolean; candidate: { lifecycle: string } } }).data.candidate.lifecycle).toBe('enabled')

    const exampleSet = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/synthetic-example-sets`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': '1', 'idempotency-key': 'chain-example-set' },
      body: JSON.stringify({
        caseKinds: ['contradiction'],
        cases: [{
          caseId: 'case-due',
          caseKind: 'contradiction',
          objectTypeRef: 'asset',
          fields: [{ fieldId: 'inspection_due', value: true }],
        }],
        expectations: [{
          expectationId: 'exp-due',
          caseId: 'case-due',
          kind: 'rule',
          ruleId: 'inspection_due_rule',
          expected: 'true',
          origin: 'authored_oracle',
          reason: 'the oracle asserts the rule fires',
          confirmedBy: 'reviewer-1',
          confirmedAt: '2026-09-30T00:00:00Z',
        }],
      }),
    })
    if (exampleSet.status !== 201) throw new Error(`synthetic example set failed: ${await failureDetail(exampleSet)}`)
    const exampleSetId = (await jsonBody(exampleSet) as { data: { exampleSet: { exampleSetId: string } } }).data.exampleSet.exampleSetId

    const validation = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/validations`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': '1', 'idempotency-key': 'chain-validation' },
      body: JSON.stringify({ exampleSetId }),
    })
    if (validation.status !== 201) throw new Error(`validation failed: ${await failureDetail(validation)}`)
    const report = (await jsonBody(validation) as { data: { validation: { validationId: string; publishable: boolean; semanticPublished: { passed: boolean }; deploymentExecutable: { passed: boolean } } } }).data.validation
    expect(report.semanticPublished.passed).toBe(true)
    expect(report.deploymentExecutable.passed).toBe(true)
    expect(report.publishable).toBe(true)

    // CAS conflict blocking: a stale revision may not publish the pack.
    const stalePublish = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/publications`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': '999', 'idempotency-key': 'chain-publish-stale' },
      body: JSON.stringify({ packId: 'chain-pack', version: '1.0.0', validationId: report.validationId }),
    })
    expect(stalePublish.status).toBe(409)

    const publish = await request(baseUrl, `/api/v1/industry-workspaces/${workspaceId}/publications`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'if-match': '1', 'idempotency-key': 'chain-publish' },
      body: JSON.stringify({ packId: 'chain-pack', version: '1.0.0', validationId: report.validationId }),
    })
    if (publish.status !== 201) throw new Error(`publish failed: ${await failureDetail(publish)}`)
    const published = await jsonBody(publish) as { data: { packRef: { id: string; version: string; digest: string } } }
    publishedPackRef = published.data.packRef
    expect(publishedPackRef.id).toBe('chain-acceptance.chain-pack')
    expect(publishedPackRef.version).toBe('1.0.0')

    const catalogue = await request(baseUrl, '/api/v1/industry-packs')
    if (catalogue.status !== 200) throw new Error(`catalogue read failed: ${await failureDetail(catalogue)}`)
    const packs = (await jsonBody(catalogue) as { data: { packs: { packRef: { id: string; version: string } }[] } }).data.packs
    expect(packs.some((entry) => entry.packRef.id === publishedPackRef?.id && entry.packRef.version === '1.0.0')).toBe(true)

    // Tenant/space isolation: another scope sees neither the workspace nor the published pack.
    const other = await startCompositionFor(otherScope)
    otherComposition = other.composition
    otherApi = other.api
    otherBaseUrl = other.baseUrl
    const foreignAdjudications = await request(otherBaseUrl, `/api/v1/industry-workspaces/${workspaceId}/definition-adjudications`)
    expect(foreignAdjudications.status).toBe(200)
    const foreignAdjudicationRows = (await jsonBody(foreignAdjudications) as { data: { adjudications: unknown[] } }).data.adjudications
    expect(foreignAdjudicationRows).toHaveLength(0)
    const foreignCatalogue = await request(otherBaseUrl, '/api/v1/industry-packs')
    expect(foreignCatalogue.status).toBe(200)
    const foreignPacks = (await jsonBody(foreignCatalogue) as { data: { packs: unknown[] } }).data.packs
    expect(foreignPacks).toHaveLength(0)
  }, 240_000)

  it('reads the published pack back through a fresh host over the same database after a restart', async () => {
    await api?.close()
    api = undefined
    await composition?.close()
    composition = undefined

    const restarted = await startCompositionFor(scope)
    composition = restarted.composition
    api = restarted.api
    baseUrl = restarted.baseUrl

    expect(publishedPackRef).toBeDefined()
    const catalogue = await request(baseUrl, '/api/v1/industry-packs')
    if (catalogue.status !== 200) throw new Error(`restart catalogue read failed: ${await failureDetail(catalogue)}`)
    const packs = (await jsonBody(catalogue) as { data: { packs: { packRef: { id: string; version: string; digest: string } }[] } }).data.packs
    const restored = packs.find((entry) => entry.packRef.id === publishedPackRef?.id && entry.packRef.version === publishedPackRef?.version)
    expect(restored?.packRef.digest).toBe(publishedPackRef?.digest)

    const exportResponse = await request(baseUrl, `/api/v1/industry-packs/${encodeURIComponent(publishedPackRef?.id ?? '')}/export?version=${encodeURIComponent(publishedPackRef?.version ?? '')}`)
    if (exportResponse.status !== 200) throw new Error(`pack export failed: ${await failureDetail(exportResponse)}`)
    const bundle = await jsonBody(exportResponse) as { data: { packRef: { id: string; version: string } } }
    expect(bundle.data.packRef.id).toBe(publishedPackRef?.id)
    expect(bundle.data.packRef.version).toBe(publishedPackRef?.version)
  }, 240_000)
})
