import { createHash } from 'node:crypto'
import { parseExecutionPreview } from '@ontology/app-web'

export const CQ_WORKSPACE = '11111111-1111-4111-8111-111111111111'
export const CQ_SOURCE = '22222222-2222-4222-8222-222222222222'
export const CQ_RULE = '33333333-3333-4333-8333-333333333333'
export const cqDigest = (bytes: Uint8Array | string) => `sha256:${createHash('sha256').update(bytes).digest('hex')}`
/** HTTP-port data only; no normal-host/PG capability claim is made by this fixture. */
export function previewWire() {
  const policy = new TextEncoder().encode('独立原始设备维护规范。'), digest = cqDigest(policy), ref = { id: 'machine.current', version: '1.0.0', digest: `sha256:${'a'.repeat(64)}` }, rule = { id: CQ_RULE, version: '1.0.0', digest: `sha256:${'b'.repeat(64)}` }, sourceRef = { id: CQ_SOURCE, version: '1.0.0', digest, kind: 'document' }
  const definition = { ref, scopeRef: { tenantId: '44444444-4444-4444-8444-444444444444', spaceId: '55555555-5555-4555-8555-555555555555' }, objects: [{ kind: 'object', id: 'machine', displayName: '设备', identityScopeId: 'machine_identity' }], attributes: [{ kind: 'attribute', id: 'machine_id', objectId: 'machine', valueType: 'string', cardinality: { min: 1, max: 1 } }, { kind: 'attribute', id: 'hours', objectId: 'machine', valueType: 'quantity', cardinality: { min: 1, max: 1 }, unit: { unitCode: 'h', dimension: 'time' } }], relations: [], identityScopes: [{ kind: 'identity_scope', id: 'machine_identity', objectId: 'machine', scopeDimensions: ['project'], identityAttributeIds: ['machine_id'] }] }
  return { purpose: 'synthetic_execution_support', businessApproval: 'none', workspace: { workspaceId: CQ_WORKSPACE, namespace: 'machine-demo', displayName: '设备本体', boundary: { goals: ['维护'], included: [], excluded: [], applicability: {} }, headRevision: '3', state: 'draft' }, draft: { workspaceId: CQ_WORKSPACE, revision: '3', digest: ref.digest, documentSetRef: { id: CQ_SOURCE, version: '1.0.0', digest, kind: 'artifact' }, candidateRefs: [] }, packRef: { id: 'machine.preview', version: '0.0.2', digest: ref.digest }, definitionRef: ref, profileRef: { id: 'machine-profile', version: '1.0.0', snapshotHash: ref.digest }, ruleRefs: [rule], ruleChoices: [{ ref: rule, ruleId: 'maintenance', objectId: 'machine', displayName: '设备维护要求', sourceRefs: [sourceRef], hasBusinessConclusion: false }], sourceRefs: [sourceRef], sources: [{ sourceRef, name: '维护规范', kind: 'document', parseId: CQ_RULE, parserVersion: '1.0.0', status: 'complete', previewCoverage: 'complete', coverage: { status: 'complete', completeness: 'complete', totalUnits: 1, parsedUnits: 1, skippedUnits: 0, skippedReasons: [], notes: [] }, byteSize: policy.byteLength, wholeSourceLocation: { sourceRef: { id: sourceRef.id, version: sourceRef.version, digest }, startOffset: 0, endOffset: policy.byteLength, quoteDigest: digest } }], templateBindingRef: { id: '66666666-6666-4666-8666-666666666666', version: '1.0.0', digest: ref.digest, kind: 'artifact' }, definitions: definition, termLabels: { attributes: [{ objectId: 'machine', attributeId: 'machine_id', displayName: '设备编号' }, { objectId: 'machine', attributeId: 'hours', displayName: '运行时长' }], relations: [] }, semanticPublished: true, deploymentExecutable: false }
}
export const currentPreview = () => parseExecutionPreview(previewWire())
