import type { Rfc3339UtcTimestamp, TimeWindow } from '@ontology/contracts'
import { EnergyInputError } from './errors'
import type { NormalizedSlot, OffsetChange, SlotAlignment } from './types'

/**
 * Explicit unit/time-zone/slot alignment (SPEC E2/E3/E4, E-03).
 *
 * Slots are generated by adding the slot length in absolute (UTC) time from the horizon start,
 * and each slot is labelled with its local wall-clock start and its UTC offset. A local day
 * that contains a DST transition therefore has 23 or 25 hours and 92 or 100 quarter-hour slots,
 * handled explicitly instead of being silently shifted to a fixed 24-hour grid.
 *
 * The local wall clock is derived with `Intl`/`hourCycle: 'h23'`, so no external time-zone
 * database is needed and the same code runs in every deployment.
 */

interface LocalFields {
  readonly year: number
  readonly month: number
  readonly day: number
  readonly hour: number
  readonly minute: number
  readonly second: number
}

type LocalFieldType = 'year' | 'month' | 'day' | 'hour' | 'minute' | 'second'

const FORMATTERS = new Map<string, Intl.DateTimeFormat>()

function formatterFor(timeZone: string): Intl.DateTimeFormat {
  const cached = FORMATTERS.get(timeZone)
  if (cached !== undefined) return cached
  if (timeZone.trim().length === 0) {
    throw new EnergyInputError('INVALID_TIME_ZONE', 'a non-empty IANA time zone is required')
  }
  let formatter: Intl.DateTimeFormat
  try {
    formatter = new Intl.DateTimeFormat('en-US', {
      timeZone,
      hourCycle: 'h23',
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    })
  } catch (error) {
    throw new EnergyInputError('INVALID_TIME_ZONE', `unknown IANA time zone: ${timeZone}`, {
      cause: error,
    })
  }
  FORMATTERS.set(timeZone, formatter)
  return formatter
}

function fieldOf(parts: readonly Intl.DateTimeFormatPart[], type: LocalFieldType): number {
  const part = parts.find((candidate) => candidate.type === type)
  if (part === undefined) {
    throw new EnergyInputError('INVALID_TIME_ZONE', `the time zone did not resolve ${type}`)
  }
  const value = Number.parseInt(part.value, 10)
  if (!Number.isFinite(value)) {
    throw new EnergyInputError('INVALID_TIME_ZONE', `the time zone resolved a non-numeric ${type}`)
  }
  return value
}

function localFieldsAt(utcMs: number, timeZone: string): LocalFields {
  const parts = formatterFor(timeZone).formatToParts(new Date(utcMs))
  return {
    year: fieldOf(parts, 'year'),
    month: fieldOf(parts, 'month'),
    day: fieldOf(parts, 'day'),
    hour: fieldOf(parts, 'hour'),
    minute: fieldOf(parts, 'minute'),
    second: fieldOf(parts, 'second'),
  }
}

export function assertTimeZone(timeZone: string): void {
  formatterFor(timeZone)
}

/** Offset of `timeZone` from UTC, in minutes, at the given instant. */
export function utcOffsetMinutesAt(utcMs: number, timeZone: string): number {
  const fields = localFieldsAt(utcMs, timeZone)
  const asUtc = Date.UTC(
    fields.year,
    fields.month - 1,
    fields.day,
    fields.hour,
    fields.minute,
    fields.second,
  )
  return Math.round((asUtc - utcMs) / 60_000)
}

function pad(value: number, width: number): string {
  return String(value).padStart(width, '0')
}

function formatLocalDateTime(utcMs: number, timeZone: string): string {
  const fields = localFieldsAt(utcMs, timeZone)
  return [
    `${pad(fields.year, 4)}-${pad(fields.month, 2)}-${pad(fields.day, 2)}`,
    `${pad(fields.hour, 2)}:${pad(fields.minute, 2)}:${pad(fields.second, 2)}`,
  ].join('T')
}

/**
 * Resolve a local wall-clock time to its UTC instant. A non-existent or ambiguous local time
 * (inside a DST jump) resolves to a defined instant rather than throwing: local *midnight* is
 * never ambiguous in the zones the fixtures use, and the slot grid itself is built in UTC.
 */
function zonedTimeToUtc(fields: LocalFields, timeZone: string): number {
  const guess = Date.UTC(
    fields.year,
    fields.month - 1,
    fields.day,
    fields.hour,
    fields.minute,
    fields.second,
  )
  const offset = utcOffsetMinutesAt(guess, timeZone)
  const candidate = guess - offset * 60_000
  const candidateOffset = utcOffsetMinutesAt(candidate, timeZone)
  return candidateOffset === offset ? candidate : guess - candidateOffset * 60_000
}

function parseLocalDate(localDate: string): { year: number; month: number; day: number } {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(localDate)
  if (match === null) {
    throw new EnergyInputError('INVALID_ARGUMENT', `local date must be YYYY-MM-DD: ${localDate}`)
  }
  const year = Number(match[1])
  const month = Number(match[2])
  const day = Number(match[3])
  if (month < 1 || month > 12 || day < 1 || day > 31) {
    throw new EnergyInputError('INVALID_ARGUMENT', `local date is out of range: ${localDate}`)
  }
  return { year, month, day }
}

export function alignSlots(
  horizon: TimeWindow,
  timeZone: string,
  slotMinutes: number,
): readonly NormalizedSlot[] {
  assertTimeZone(timeZone)
  if (!Number.isInteger(slotMinutes) || slotMinutes <= 0) {
    throw new EnergyInputError('INVALID_ARGUMENT', 'slotMinutes must be a positive integer')
  }
  const slotMs = slotMinutes * 60_000
  const startMs = Date.parse(horizon.start)
  const endMs = Date.parse(horizon.end)
  if (!Number.isFinite(startMs) || !Number.isFinite(endMs) || endMs <= startMs) {
    throw new EnergyInputError('INVALID_ARGUMENT', 'the horizon must be a non-empty [start, end) window')
  }
  const span = endMs - startMs
  if (span % slotMs !== 0) {
    throw new EnergyInputError(
      'MISALIGNED_HORIZON',
      `the horizon span of ${span} ms is not a whole number of ${slotMinutes}-minute slots`,
    )
  }
  const count = span / slotMs
  const slots: NormalizedSlot[] = []
  for (let index = 0; index < count; index += 1) {
    const slotStart = startMs + index * slotMs
    const slotEnd = slotStart + slotMs
    slots.push({
      index,
      startUtc: new Date(slotStart).toISOString(),
      endUtc: new Date(slotEnd).toISOString(),
      localStart: formatLocalDateTime(slotStart, timeZone),
      utcOffsetMinutes: utcOffsetMinutesAt(slotStart, timeZone),
    })
  }
  return slots
}

export function summarizeAlignment(
  slots: readonly NormalizedSlot[],
  timeZone: string,
  slotMinutes: number,
): SlotAlignment {
  const first = slots[0]
  const last = slots[slots.length - 1]
  if (first === undefined || last === undefined) {
    throw new EnergyInputError('INVALID_ARGUMENT', 'at least one slot is required to summarise alignment')
  }
  const offsetChanges: OffsetChange[] = []
  let previous = first.utcOffsetMinutes
  for (const slot of slots) {
    if (slot.utcOffsetMinutes !== previous) {
      offsetChanges.push({
        atSlotIndex: slot.index,
        fromMinutes: previous,
        toMinutes: slot.utcOffsetMinutes,
      })
      previous = slot.utcOffsetMinutes
    }
  }
  const startMs = Date.parse(first.startUtc)
  const endMs = Date.parse(last.endUtc)
  return {
    timeZone,
    slotMinutes,
    slotCount: slots.length,
    horizonHours: (endMs - startMs) / 3_600_000,
    offsetChanges,
  }
}

export interface LocalDayAlignment {
  readonly horizon: TimeWindow
  readonly slots: readonly NormalizedSlot[]
  readonly alignment: SlotAlignment
}

/**
 * The `[local midnight, next local midnight)` window for a calendar date. On a spring-forward
 * day this is 23 hours (92 quarter-hour slots); on a fall-back day 25 hours (100 slots).
 */
export function localDayWindow(
  localDate: string,
  timeZone: string,
  slotMinutes: number,
): LocalDayAlignment {
  const { year, month, day } = parseLocalDate(localDate)
  const startMs = zonedTimeToUtc({ year, month, day, hour: 0, minute: 0, second: 0 }, timeZone)
  const nextCalendar = new Date(Date.UTC(year, month - 1, day))
  nextCalendar.setUTCDate(nextCalendar.getUTCDate() + 1)
  const endMs = zonedTimeToUtc(
    {
      year: nextCalendar.getUTCFullYear(),
      month: nextCalendar.getUTCMonth() + 1,
      day: nextCalendar.getUTCDate(),
      hour: 0,
      minute: 0,
      second: 0,
    },
    timeZone,
  )
  const horizon: TimeWindow = {
    start: new Date(startMs).toISOString(),
    end: new Date(endMs).toISOString(),
  }
  const slots = alignSlots(horizon, timeZone, slotMinutes)
  return { horizon, slots, alignment: summarizeAlignment(slots, timeZone, slotMinutes) }
}

export function slotIndexFor(
  timestamp: Rfc3339UtcTimestamp,
  horizon: TimeWindow,
  slotMinutes: number,
): number | undefined {
  const slotMs = slotMinutes * 60_000
  const startMs = Date.parse(horizon.start)
  const endMs = Date.parse(horizon.end)
  const timestampMs = Date.parse(timestamp)
  if (!Number.isFinite(timestampMs) || timestampMs < startMs || timestampMs >= endMs) {
    return undefined
  }
  return Math.floor((timestampMs - startMs) / slotMs)
}
