import { isRecord } from '@ontology/contracts'
import { Field } from '../ui'
const stateLabels: Readonly<Record<string, string>> = { true: '成立', false: '不成立', unknown: '未知', conflict: '冲突', applicable: '适用', not_applicable: '不适用' }
export function ExpectationEditor({ value, onChange, disabled }: { readonly value: unknown; readonly onChange: (value: unknown) => void; readonly disabled: boolean }) {
  if (!isRecord(value)) return <p>此独立期望结构暂不能通过表单编辑，完整保留在高级详情。</p>
  if (value['kind'] === 'rule') return <fieldset disabled={disabled}><legend>独立期望的规则判断</legend><div className="ontology-form-grid">{(['conditionState', 'applicability', 'propositionState'] as const).map((key) => <Field key={key} label={{ conditionState: '条件状态', applicability: '适用状态', propositionState: '命题状态' }[key]}>{(a) => <select {...a} value={String(value[key])} onChange={(e) => onChange({ ...value, [key]: e.target.value })}>{(key === 'applicability' ? ['applicable', 'not_applicable', 'unknown', 'conflict'] : ['true', 'false', 'unknown', 'conflict']).map((state) => <option key={state} value={state}>{stateLabels[state]}</option>)}</select>}</Field>)}</div></fieldset>
  if (value['kind'] === 'unknown') return <Field label="期望未知的独立原因">{(a) => <textarea {...a} disabled={disabled} value={String(value['reason'])} onChange={(e) => onChange({ ...value, reason: e.target.value })} />}</Field>
  if (value['kind'] === 'refusal') return <Field label="期望拒绝的原因">{(a) => <select {...a} disabled={disabled} value={String(value['reason'])} onChange={(e) => onChange({ ...value, reason: e.target.value })}><option value="cross_project">请求跨越项目边界</option><option value="definition_version_mismatch">定义版本不匹配</option><option value="unit_mismatch">单位不匹配</option><option value="unsupported_capability">缺少所需能力</option></select>}</Field>
  if (value['kind'] === 'relation') return <div><p>关系目标由真实原文与身份绑定约定；目标标识在高级内容中完整保留。</p><Field label="期望覆盖程度">{(a) => <select {...a} disabled={disabled} value={String(value['completeness'])} onChange={(e) => onChange({ ...value, completeness: e.target.value })}><option value="complete">完整</option><option value="partial">部分</option><option value="unknown">未知</option></select>}</Field></div>
  if (value['kind'] !== 'value') return <p>此期望类型暂不提供编辑表单，保留原始内容。</p>
  const scalar = value['value']
  if (typeof scalar === 'boolean') return <Field label="独立期望结果">{(a) => <select {...a} disabled={disabled} value={String(scalar)} onChange={(e) => onChange({ ...value, value: e.target.value === 'true' })}><option value="true">是</option><option value="false">否</option></select>}</Field>
  if (typeof scalar === 'string') return <Field label="独立期望结果">{(a) => <input {...a} disabled={disabled} value={scalar} onChange={(e) => onChange({ ...value, value: e.target.value })} />}</Field>
  if (isRecord(scalar) && typeof scalar['amount'] === 'string') return <div className="ontology-form-grid"><Field label="独立期望精确数值" hint="保留十进制原文，不由实际结果回填。">{(a) => <input {...a} disabled={disabled} inputMode="decimal" value={String(scalar['amount'])} onChange={(e) => onChange({ ...value, value: { ...scalar, amount: e.target.value } })} />}</Field>{typeof scalar['unit'] === 'string' ? <Field label="期望单位">{(a) => <input {...a} disabled={disabled} value={String(scalar['unit'])} onChange={(e) => onChange({ ...value, value: { ...scalar, unit: e.target.value } })} />}</Field> : typeof scalar['currency'] === 'string' ? <Field label="期望币种">{(a) => <input {...a} disabled={disabled} value={String(scalar['currency'])} onChange={(e) => onChange({ ...value, value: { ...scalar, currency: e.target.value } })} />}</Field> : null}</div>
  return <p>原始期望值完整保留，请在高级详情核对。</p>
}
