import type { DefinitionChange, DefinitionRevisionStrategy, VersionRef } from '@ontology/contracts'
import type { PackVersionChangeView } from '../../api/package-publication'
import { Button, Field, StatusBadge } from '../ui'
export function FullVersionDiff({ changes, labels = new Map() }: { readonly changes: readonly (DefinitionChange | PackVersionChangeView)[]; readonly labels?: ReadonlyMap<string, string> }) {
  const group = (value: DefinitionChange | PackVersionChangeView) => { const code = 'code' in value ? value.code : value.change; return /ADDED|added|add$/.test(code) ? '新增' : /REMOVED|removed|deleted|remove$/.test(code) ? '删除' : '变更' }
  return <section className="ontology-full-diff"><h3>完整版本差异</h3>{changes.length === 0 ? <p>服务端未发现差异。</p> : ['新增', '变更', '删除'].map((name) => <section key={name}><h4>{name}（{changes.filter((c) => group(c) === name).length}）</h4>{changes.filter((c) => group(c) === name).map((change, i) => <article key={`${change.logicalId}:${i}`} className="ontology-diff-item"><header className="ontology-pane-heading"><strong>{labels.get(change.logicalId) ?? change.logicalId}</strong><StatusBadge tone={change.breaking ? 'warning' : 'neutral'}>{change.breaking ? '破坏性变更' : '兼容变更'}</StatusBadge></header><p>{change.message}</p><div className="ontology-form-grid"><div><h5>变更前</h5><p>{change.before ?? '无此项'}</p></div><div><h5>变更后</h5><p>{change.after ?? '无此项'}</p></div></div><details><summary>差异标识</summary><pre>{JSON.stringify(change, null, 2)}</pre></details></article>)}</section>)}</section>
}
export function RevisionStrategyForm({ value, onChange, previous, disabled = false, onValidate }: { readonly value: DefinitionRevisionStrategy | undefined; readonly onChange: (value: DefinitionRevisionStrategy | undefined) => void; readonly previous?: VersionRef; readonly disabled?: boolean; readonly onValidate?: () => void }) {
  return <fieldset disabled={disabled} className="ontology-fields"><legend>版本处理策略</legend><p>破坏性变更必须显式选择处理方式；旧实例和历史答案保持自己的版本。</p><Field label="如何处理旧版本">{(a) => <select {...a} value={value?.kind ?? ''} onChange={(e) => {
    const kind = e.target.value
    if (kind === 'new_version' || kind === 'keep_independent' || kind === 'retire_previous') onChange({ kind, reason: value?.reason ?? '', ...(previous === undefined ? {} : { supersedesRef: previous }) })
    else onChange(undefined)
  }}><option value="">请选择策略</option><option value="new_version">发布新版本，保留历史</option><option value="keep_independent">新旧含义保持独立</option><option value="retire_previous">明确停用旧版本</option></select>}</Field><Field label="选择该策略的原因">{(a) => <textarea {...a} value={value?.reason ?? ''} disabled={disabled || value === undefined} onChange={(e) => { if (value !== undefined) onChange({ ...value, reason: e.target.value }) }} />}</Field>{onValidate === undefined ? null : <Button disabled={disabled || value === undefined || !value.reason.trim()} onClick={onValidate}>按此策略重新验核</Button>}{previous === undefined ? <p className="ontology-hint">当前未读取到可取代的精确旧版本；服务端会校验策略适用性。</p> : <details><summary>策略绑定的旧版本</summary><pre>{JSON.stringify(previous, null, 2)}</pre></details>}</fieldset>
}
