/**
 * @ontology/contracts — canonical cross-process contracts (INV-01).
 *
 * This package contains only data types, JSON Schema, version and error definitions.
 * It imports no SDK, database, HTTP or industry package. The TypeScript types are
 * generated from `schema/*.schema.json`; `pnpm --filter @ontology/contracts run
 * check:contracts` fails when the committed output drifts from the canonical schema.
 */
export * from './generated/contracts'
export * from './generated/schema-bundle'
export * from './generated/tool-catalogue'
export * from './generated/error-catalogue'
export * from './ports'
export * from './budget'
export * from './component-registry'
export * from './semantic-definitions'
export * from './profile-store'
export * from './source-bindings'
export * from './web-search'
export * from './run-store'
export * from './feedback'
export * from './job-store'
export * from './document-parse'
export * from './structured-parse'
export * from './structured-ingestion'
export * from './extraction'
export * from './identity-decisions'
export * from './decision-state'
export * from './rule-extraction'
export * from './semantic-publication'
export * from './materialization'
export * from './evidence-store'
export * from './provenance-read'
export * from './trusted'
export * from './operations'
export * from './compute'
export * from './semver'
export * from './industry-packs'
export * from './pack-assets'
export * from './preflight'
export * from './verification'
export * from './workflow'
export * from './workflow-dispatch'
export * from './planning'
export * from './few-shot'
export * from './schema-vocabulary'
export * from './asset-workspace'
export * from './asset-candidates'
export * from './projects'
