import { randomBytes } from 'node:crypto'
import { chmod, mkdir, readFile, rename, unlink, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { setTimeout as delay } from 'node:timers/promises'
import { Client } from 'pg'
import { runControlMigrations } from '@ontology/adapter-control-postgres'

export const CORE_DEMO_TENANT_ID = '11111111-1111-4111-8111-111111111111'
export const CORE_DEMO_SPACE_ID = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'
export const CORE_DATABASE_NAME = 'ontology_core'
export const CORE_APP_ROLE = 'ontology_app'

const DEFAULT_API_PORT = 3001
const DEFAULT_WEB_PORT = 5174
const DEFAULT_PG_PORT = 54330
const DB_CONNECT_TIMEOUT_MS = 25_000
const DB_RETRY_DELAY_MS = 500
const PLATFORM_ROOT = fileURLToPath(new URL('..', import.meta.url))
const MIGRATIONS_DIR = resolve(PLATFORM_ROOT, 'migrations', 'control')
const LOCAL_ENV_PATH = resolve(PLATFORM_ROOT, '.env.core.local')

export interface CorePreparationOptions {
  readonly controlDatabaseUrl: string
  readonly controlHost: string
  readonly pgPort: number
  readonly appPassword: string
  readonly appDatabaseUrl: string
  readonly apiPort: number
  readonly webPort: number
  readonly tenantId: string
  readonly spaceId: string
}

/** Resolve only the local core configuration; never fall back to an old/global database URL. */
export function resolveCorePreparationOptions(
  env: Readonly<Record<string, string | undefined>>,
): CorePreparationOptions {
  const controlDatabaseUrl = required(env, 'CORE_CONTROL_DATABASE_URL')
  let controlUrl: URL
  try {
    controlUrl = new URL(controlDatabaseUrl)
  } catch {
    throw new Error('CORE_CONTROL_DATABASE_URL must be a PostgreSQL URL for this local core database')
  }
  if (controlUrl.protocol !== 'postgres:' && controlUrl.protocol !== 'postgresql:') {
    throw new Error('CORE_CONTROL_DATABASE_URL must use the postgres or postgresql scheme')
  }
  if (controlUrl.username.length === 0 || controlUrl.hostname.length === 0) {
    throw new Error('CORE_CONTROL_DATABASE_URL must include a database user and host')
  }
  const controlHost = controlUrl.hostname.toLowerCase()
  if (controlHost !== '127.0.0.1' && controlHost !== 'localhost' && controlHost !== '[::1]') {
    throw new Error('CORE_CONTROL_DATABASE_URL must target loopback; core preparation never targets a remote database')
  }

  const pgPort = readPort(env['CORE_PG_PORT'], DEFAULT_PG_PORT, 'CORE_PG_PORT')
  const controlPort = controlUrl.port.length === 0 ? 5432 : Number(controlUrl.port)
  if (controlPort !== pgPort) {
    throw new Error('CORE_CONTROL_DATABASE_URL port must match CORE_PG_PORT (default 54330)')
  }
  const databaseName = decodeURIComponent(controlUrl.pathname.replace(/^\//u, ''))
  if (databaseName !== CORE_DATABASE_NAME) {
    throw new Error(`CORE_CONTROL_DATABASE_URL must target ${CORE_DATABASE_NAME}`)
  }

  const appPassword = env['CORE_APP_PASSWORD'] ?? randomBytes(24).toString('base64url')
  if (!/^[A-Za-z0-9_-]{16,256}$/u.test(appPassword)) {
    throw new Error('CORE_APP_PASSWORD must be 16–256 URL-safe characters (letters, digits, underscore, or hyphen)')
  }
  const appUrl = new URL(controlDatabaseUrl)
  appUrl.username = CORE_APP_ROLE
  appUrl.password = appPassword

  const apiPort = readPort(env['CORE_API_PORT'], DEFAULT_API_PORT, 'CORE_API_PORT')
  const webPort = readPort(env['CORE_WEB_PORT'], DEFAULT_WEB_PORT, 'CORE_WEB_PORT')
  const legacyPorts = new Set([3_000, 5_173, 54_329])
  if ([apiPort, webPort, pgPort].some((port) => legacyPorts.has(port))) {
    throw new Error('Core ports must stay isolated from the existing 3000/5173/54329 services')
  }
  if (new Set([apiPort, webPort, pgPort]).size !== 3) {
    throw new Error('CORE_API_PORT, CORE_WEB_PORT, and CORE_PG_PORT must be distinct')
  }

  return {
    controlDatabaseUrl,
    controlHost,
    pgPort,
    appPassword,
    appDatabaseUrl: appUrl.toString(),
    apiPort,
    webPort,
    tenantId: readUuid(env['CORE_TENANT_ID'], CORE_DEMO_TENANT_ID, 'CORE_TENANT_ID'),
    spaceId: readUuid(env['CORE_SPACE_ID'], CORE_DEMO_SPACE_ID, 'CORE_SPACE_ID'),
  }
}

/** App-only local config. Admin URLs and server passwords are deliberately excluded. */
export function serializeCoreLocalEnvironment(options: CorePreparationOptions): string {
  return [
    '# Generated by scripts/prepare-core-db.ts; ignored by git.',
    '# Contains only local non-superuser app credentials/config. Keep this file local.',
    `CORE_DATABASE_URL=${options.appDatabaseUrl}`,
    `CORE_APP_PASSWORD=${options.appPassword}`,
    `CORE_API_PORT=${String(options.apiPort)}`,
    `CORE_WEB_PORT=${String(options.webPort)}`,
    `CORE_PG_PORT=${String(options.pgPort)}`,
    `CORE_TENANT_ID=${options.tenantId}`,
    `CORE_SPACE_ID=${options.spaceId}`,
    `VITE_CORE_API_PORT=${String(options.apiPort)}`,
    'VITE_API_BASE_URL=',
    'CORE_ENABLE_MODELS=false',
    '',
  ].join('\n')
}

async function waitForDatabase(connectionString: string): Promise<void> {
  const deadline = Date.now() + DB_CONNECT_TIMEOUT_MS
  for (;;) {
    const client = new Client({
      connectionString,
      connectionTimeoutMillis: 1_500,
      application_name: 'ontology-core-prepare-probe',
    })
    try {
      await client.connect()
      const result = await client.query<{ database: string }>('SELECT current_database() AS database')
      if (result.rows[0]?.database !== CORE_DATABASE_NAME) {
        throw new Error('CORE_CONTROL_DATABASE_URL connected to an unexpected database')
      }
      return
    } catch {
      if (Date.now() >= deadline) {
        throw new Error('Core PostgreSQL did not become reachable within 25 seconds; check the local compose service and its health')
      }
      await delay(DB_RETRY_DELAY_MS)
    } finally {
      await client.end().catch(() => undefined)
    }
  }
}

async function connectAdmin(connectionString: string): Promise<Client> {
  const client = new Client({
    connectionString,
    connectionTimeoutMillis: 2_000,
    application_name: 'ontology-core-prepare',
  })
  try {
    await client.connect()
    return client
  } catch {
    await client.end().catch(() => undefined)
    throw new Error('Core admin connection failed after PostgreSQL became ready; verify local credentials')
  }
}

async function configureAppRole(client: Client, appPassword: string): Promise<void> {
  const formatted = await client.query<{ statement: string }>(
    "SELECT format('ALTER ROLE ontology_app WITH LOGIN PASSWORD %L', $1::text) AS statement",
    [appPassword],
  )
  const statement = formatted.rows[0]?.statement
  if (statement === undefined) throw new Error('Could not prepare the application role configuration')
  await client.query(statement)

  const result = await client.query<{
    rolcanlogin: boolean
    rolsuper: boolean
    rolcreatedb: boolean
    rolcreaterole: boolean
    rolbypassrls: boolean
  }>(
    `SELECT rolcanlogin, rolsuper, rolcreatedb, rolcreaterole, rolbypassrls
       FROM pg_roles WHERE rolname = $1`,
    [CORE_APP_ROLE],
  )
  const role = result.rows[0]
  if (
    role === undefined || !role.rolcanlogin || role.rolsuper || role.rolcreatedb ||
    role.rolcreaterole || role.rolbypassrls
  ) {
    throw new Error('The migrated ontology_app role is missing or has unsafe PostgreSQL privileges')
  }
}

async function configureDemoScope(
  client: Client,
  tenantId: string,
  spaceId: string,
): Promise<void> {
  const slug = 'ontology-core-local'
  const tenant = await client.query<{ tenant_id: string; slug: string }>(
    `SELECT tenant_id::text AS tenant_id, slug
       FROM agent_platform.tenants
      WHERE tenant_id = $1::uuid OR slug = $2`,
    [tenantId, slug],
  )
  if (tenant.rows.length === 0) {
    await client.query(
      'INSERT INTO agent_platform.tenants (tenant_id, slug) VALUES ($1::uuid, $2)',
      [tenantId, slug],
    )
  } else if (
    tenant.rows.length !== 1 || tenant.rows[0]?.tenant_id !== tenantId || tenant.rows[0]?.slug !== slug
  ) {
    throw new Error('The configured core demo tenant id or slug conflicts with existing local control data')
  }

  const spaceName = 'Core local demo'
  const space = await client.query<{ name: string }>(
    `SELECT name FROM agent_platform.spaces
      WHERE tenant_id = $1::uuid AND space_id = $2::uuid`,
    [tenantId, spaceId],
  )
  if (space.rows.length === 0) {
    await client.query(
      'INSERT INTO agent_platform.spaces (tenant_id, space_id, name) VALUES ($1::uuid, $2::uuid, $3)',
      [tenantId, spaceId, spaceName],
    )
  } else if (space.rows.length !== 1 || space.rows[0]?.name !== spaceName) {
    throw new Error('The configured core demo space id conflicts with existing local control data')
  }
}

async function verifyAppConnection(connectionString: string): Promise<void> {
  const client = new Client({
    connectionString,
    connectionTimeoutMillis: 2_000,
    application_name: 'ontology-core-app-check',
  })
  try {
    await client.connect()
    const result = await client.query<{ current_user: string; current_database: string }>(
      'SELECT current_user, current_database()',
    )
    if (result.rows[0]?.current_user !== CORE_APP_ROLE || result.rows[0]?.current_database !== CORE_DATABASE_NAME) {
      throw new Error('Unexpected local application database identity')
    }
  } catch {
    await client.end().catch(() => undefined)
    throw new Error('The non-superuser ontology_app database connection could not be verified')
  }
  await client.end()
}

async function writeCoreEnvironment(path: string, contents: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true })
  const temporary = `${path}.tmp-${process.pid}-${randomBytes(4).toString('hex')}`
  try {
    await writeFile(temporary, contents, { encoding: 'utf8', mode: 0o600, flag: 'wx' })
    await rename(temporary, path)
    await chmod(path, 0o600).catch(() => undefined)
  } catch {
    await unlink(temporary).catch(() => undefined)
    throw new Error('Could not write the ignored .env.core.local file')
  }
}

async function readStoredAppPassword(path: string): Promise<string | undefined> {
  try {
    const contents = await readFile(path, 'utf8')
    const match = /^CORE_APP_PASSWORD=([A-Za-z0-9_-]{16,256})\s*$/mu.exec(contents)
    return match?.[1]
  } catch {
    return undefined
  }
}

async function main(): Promise<void> {
  const storedAppPassword = process.env['CORE_APP_PASSWORD'] === undefined
    ? await readStoredAppPassword(LOCAL_ENV_PATH)
    : undefined
  const options = resolveCorePreparationOptions({
    ...process.env,
    ...(process.env['CORE_APP_PASSWORD'] !== undefined || storedAppPassword === undefined
      ? {}
      : { CORE_APP_PASSWORD: storedAppPassword }),
  })
  await waitForDatabase(options.controlDatabaseUrl)

  try {
    const report = await runControlMigrations({
      connectionString: options.controlDatabaseUrl,
      migrationsDir: MIGRATIONS_DIR,
    })
    const admin = await connectAdmin(options.controlDatabaseUrl)
    try {
      await configureAppRole(admin, options.appPassword)
      await configureDemoScope(admin, options.tenantId, options.spaceId)
    } finally {
      await admin.end()
    }
    await verifyAppConnection(options.appDatabaseUrl)
    await writeCoreEnvironment(LOCAL_ENV_PATH, serializeCoreLocalEnvironment(options))
    process.stdout.write(
      `Core control database prepared. Migrations: ${String(report.applied.length)} applied, ${String(report.skipped.length)} current.\n` +
      `Application scope: ${options.tenantId} / ${options.spaceId}. Local config written to .env.core.local.\n` +
      'Admin URL, server password, and app password were not printed.\n',
    )
  } catch {
    throw new Error('Core database preparation failed. Check the local PostgreSQL health, migration status, and required roles; sensitive connection data was omitted.')
  }
}

function required(env: Readonly<Record<string, string | undefined>>, name: string): string {
  const value = env[name]
  if (value === undefined || value.length === 0) throw new Error(`${name} is required`)
  return value
}

function readPort(value: string | undefined, fallback: number, name: string): number {
  if (value === undefined || value.length === 0) return fallback
  if (!/^[1-9]\d{0,4}$/u.test(value)) throw new Error(`${name} must be an integer between 1 and 65535`)
  const port = Number(value)
  if (port > 65_535) throw new Error(`${name} must be an integer between 1 and 65535`)
  return port
}

function readUuid(value: string | undefined, fallback: string, name: string): string {
  const candidate = value ?? fallback
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/iu.test(candidate)) {
    throw new Error(`${name} must be a UUID`)
  }
  return candidate.toLowerCase()
}

const invokedPath = process.argv[1]
if (invokedPath !== undefined && pathToFileURL(resolve(invokedPath)).href === import.meta.url) {
  main().catch((error: unknown) => {
    const message = error instanceof Error ? error.message : 'unexpected error'
    process.stderr.write(`Core database preparation failed: ${message}\n`)
    process.exitCode = 1
  })
}
